"""M23: auth_flow is a wired, verified class (was declared but a silent no-op).

It is LLM-driven (like the LLM side of price/workflow): the intent model proposes
an auth-sequence invariant, the hypothesis engine generates a concrete test, and
the existing invariant-assertion / state-delta oracles confirm it. State-changing
(resets / verifications mutate) → gated in dry-run.
"""
from __future__ import annotations

import json
from pathlib import Path

import httpx
from rich.console import Console

from heretic.config import Accounts, Config, LoginSpec, Role, Scope
from heretic.core.hypothesis import LLM_CLASSES
from heretic.core.oracle import _REMEDIATION, _SEVERITY
from heretic.core.orchestrator import STATE_CHANGING, Orchestrator
from heretic.llm.scripted import ScriptedLLM

_INTENT = {"invariants": [
    {"id": "INV-1", "rule": "an account becomes verified only via the real flow", "bug_class": "auth_flow"}]}
_HYPS = [{
    "invariant_id": "INV-1", "bug_class": "auth_flow",
    "description": "set verified=true directly, skipping the verification step",
    "request_sequence": [{"method": "POST", "url": "/api/verify", "as": "userA", "body": {"verified": True}}],
    "expected_safe": "verification state is server-controlled",
    "oracle": "invariant_assertion", "assertion": {"field": "verified", "equals": True},
}]


def test_auth_flow_is_wired():
    assert "auth_flow" in LLM_CLASSES                    # generated by the hypothesis engine
    assert "auth_flow" in _SEVERITY and "auth_flow" in _REMEDIATION
    assert "auth_flow" in STATE_CHANGING                # writes are live-gated


def _vuln(req: httpx.Request) -> httpx.Response:
    if req.url.path == "/login":
        return httpx.Response(200, json={"token": "tok-a"})
    if req.url.path == "/api/verify":
        body = json.loads(req.content or b"{}")
        return httpx.Response(200, json={"verified": body.get("verified", False)})   # trusts the client
    return httpx.Response(404, json={})


def _safe(req: httpx.Request) -> httpx.Response:
    if req.url.path == "/login":
        return httpx.Response(200, json={"token": "tok-a"})
    if req.url.path == "/api/verify":
        return httpx.Response(200, json={"verified": False})                         # server-controlled
    return httpx.Response(404, json={})


def _cfg(mode: str = "live") -> Config:
    return Config(
        url="http://app.local", model="fake", engagement="t", authorized_by="t@t", signed=True,
        max_rate_rps=100000, scope=Scope(allow=["app.local"]), classes=["auth_flow"],
        mode=mode, destructive_allowed=["*"], chain=False, accounts_path=Path("accounts.yaml"),
        accounts=Accounts(login=LoginSpec(url="/login", token_field="token"),
                          roles=[Role(name="guest", creds=None),
                                 Role(name="userA", creds={"email": "a@x", "password": "x"})]))


def _run(handler, mode="live"):
    llm = ScriptedLLM(intent=_INTENT, hypotheses=_HYPS)
    orch = Orchestrator(_cfg(mode), console=Console(quiet=True),
                        transport=httpx.MockTransport(handler), llm=llm)
    return [f for f in orch.run() if f.bug_class == "auth_flow"]


def test_auth_flow_confirmed_live():
    a = _run(_vuln)
    assert len(a) == 1
    assert a[0].severity.value == "high"
    assert a[0].proof["field"] == "verified"


def test_auth_flow_server_controlled_not_flagged():
    assert _run(_safe) == []                             # server ignored client value → no FP


def test_auth_flow_gated_in_dry_run():
    assert _run(_vuln, mode="dry-run") == []             # state-changing → skipped without live mode
